name: Deploy to Vercel

on:
  push:
    branches:
      - master # or 'dev' if you deploy from dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project (optional for Next.js)
        run: yarn build

      - name: Deploy to Vercel
        run: |
          npm i -g vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm \
                 --org ${{ secrets.VERCEL_ORG_ID }} \
                 --project ${{ secrets.VERCEL_PROJECT_ID }}
